# Machine Learning / Python Interview Questions

**Note:**  
This notebook contains **Questions 1 to 20**.  
The next set of questions (21 to 40) will be covered in the **next notebook**.

---

### Summary of What We Covered

- Swapping variables without a third variable  
- String manipulation (reversing words, extracting substrings)  
- Lists, tuples, arrays, and dictionaries  
- Loops, functions, and arithmetic operations  
- Random number generation and NumPy array creation  
- DataFrame creation from dictionaries  
- Object-Oriented Programming concepts: multiple inheritance  
- Iterating over lists and strings  

All solutions are explained **step-by-step** and written in a **professional, interview-ready style**. by Vinod Bavage


### 1. Write a program to swap two variables without using 3rd variable.

In [10]:
a = 5
b = 10

print("--- This is standred Pythonic way to swap the variables values without using third variable ---")

print(f"Before swaping variable values: \n a = {a} \n b = {b}")

a,b = b, a

print(f"After Swaping variables values : \n a = {a} \n b = {b}")

--- This is standred Pythonic way to swap the variables values without using third variable ---
Before swaping variable values: 
 a = 5 
 b = 10
After Swaping variables values : 
 a = 10 
 b = 5


### 2. Reverse a string: "this is my book" expected output: "book my is this"


In [25]:
text = "this is my book"

words = text.split() # Splits the string based on spaces
print(f"Spliting the string : \n - {words}")

reverse_words = words[::-1] # [::-1] reverses the list, the op ['book', 'my', 'is', 'this']
print(f"reversing the list : \n -{reverse_words}")
result = " ".join(reverse_words)  # Joins words using a single space

print(f"Joining the words in single space : \n -{result}")

print(f'Final op \n {result}')

Spliting the string : 
 - ['this', 'is', 'my', 'book']
reversing the list : 
 -['book', 'my', 'is', 'this']
Joining the words in single space : 
 -book my is this
Final op 
 book my is this


### 3. Create a list and a tuple and differentiate them.


In [26]:
# List
my_list = [1, 2, 3, 4]

# Tuple
my_tuple = (1, 2, 3, 4)

print(my_list)
print(my_tuple)

[1, 2, 3, 4]
(1, 2, 3, 4)


# Difference Between List and Tuple

| Feature | List | Tuple |
|---------|------|-------|
| Definition | Ordered collection of elements | Ordered collection of elements |
| Mutability | Mutable (can be modified) | Immutable (cannot be modified) |
| Syntax | Square brackets `[]` | Parentheses `()` |
| Performance | Slower compared to tuple | Faster due to immutability |
| Memory Usage | Takes more memory | Takes less memory |
| Methods Available | More built-in methods | Fewer built-in methods |
| Use Case | When data needs to change | When data should remain constant |

### 4. "I am a Data Scientist".... expected output: "ataD"


In [51]:
# from INDEXING and SLICING
text = "I am a Data Scientist"

print(text[10:6:-1])
print(text[-11:-15:-1])

ataD
ataD


In [50]:
# from For-Loop
word = text.split()

for i in words:
    if i == "Data":
        result = i[::-1]
        print(result)

ataD


### 5. Create a list of odd numbers between 11-30


In [60]:
# Simple and easy method
list = []
for i in range(11,31,2):
    list.append(i)

list

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [59]:
# For good practice

odd_numbers = []

for i in range(11,31):
    if i % 2 != 0:
        odd_numbers.append(i)
print(odd_numbers)

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


In [61]:
# Advance python method 
odd_numbers = [i for i in range(11, 31) if i % 2 != 0]
print(odd_numbers)

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


### 6. Create 1D array using arange() and convert that 1D array to 3D array 


In [70]:
import numpy as np

# create 1D array
arr_1d = np.arange(24)
print(f"1D array : {arr_1d}")

# Convert to 2D array 
array_2d = arr_1d.reshape(2,3,4)
print(array_2d)

1D array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 7. Create an array with random numbers


In [75]:
arr = np.random.randint(1,100,10)
arr

array([86, 26, 18, 42,  5,  6, 30, 32, 52, 95], dtype=int32)

### 8. Create a dictionary and convert that to a dataframe such that it has 4 rows and 2 columns


In [85]:
import pandas as pd 

d = { "Name" : ["Vinod", "bhavi", "golu", "molu"],
    "Mobile_no" : [6303608901, 9874561230, 8564987124, 9621457856]}
df = pd.DataFrame(d)
df

Name   Mobile_no
0  Vinod  6303608901
1  bhavi  9874561230
2   golu  8564987124
3   molu  9621457856

### 9. What is the difference between list and array and explain with example?


# Difference Between List and Array

## Overview
Lists and arrays are both used to store collections of elements, but they have key differences in terms of functionality, data types, and performance.

## Key Differences

| Feature | List | Array |
|---------|------|-------|
| Module | Built-in Python data structure | Requires `array` module or `numpy` |
| Data Types | Can store different data types | Stores elements of the same data type |
| Size | Dynamic (can grow or shrink) | Fixed or dynamic depending on implementation |
| Performance | Slower for numerical operations | Faster for numerical computations |
| Operations | Limited mathematical operations | Supports vectorized operations (numpy) |
| Memory | Uses more memory | More memory efficient |
| Flexibility | More flexible | Less flexible, more structured |

## Examples

### List Example
```python
# Creating a list with different data types
my_list = [1, 2.5, "Hello", True, [3, 4]]

# List operations
my_list.append(10)
my_list[0] = 100
print(my_list)  # Output: [100, 2.5, 'Hello', True, [3, 4], 10]

# Lists can contain mixed data types
mixed_list = [1, "two", 3.0, [4, 5]]
print(mixed_list)  # Output: [1, 'two', 3.0, [4, 5]]
```

### Array Example (using array module)
```python
import array

# Creating an array with homogeneous data (integers only)
my_array = array.array('i', [1, 2, 3, 4, 5])

# Array operations
my_array.append(6)
my_array[0] = 10
print(my_array)  # Output: array('i', [10, 2, 3, 4, 5, 6])

# This will cause an error - arrays must contain same data type
# my_array.append("Hello")  # TypeError
```

### NumPy Array Example
```python
import numpy as np

# Creating a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

# Vectorized operations (much faster than lists)
result = numpy_array * 2
print(result)  # Output: [ 2  4  6  8 10]

# Mathematical operations
sum_result = numpy_array + np.array([10, 20, 30, 40, 50])
print(sum_result)  # Output: [11 22 33 44 55]

# Multi-dimensional arrays
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
# Output:
# [[1 2 3]
#  [4 5 6]]
```

## When to Use What?

### Use Lists When:
- You need to store mixed data types
- You need flexibility in adding/removing elements
- You're working with general-purpose data
- Performance is not critical

### Use Arrays When:
- You need to store homogeneous data (same type)
- You're performing mathematical/numerical operations
- Memory efficiency is important
- You need better performance for large datasets
- You're doing scientific computing (use NumPy)

## Performance Comparison
```python
import time
import numpy as np

# List performance
list_data = list(range(1000000))
start = time.time()
list_result = [x * 2 for x in list_data]
print(f"List time: {time.time() - start} seconds")

# NumPy array performance
array_data = np.array(range(1000000))
start = time.time()
array_result = array_data * 2
print(f"Array time: {time.time() - start} seconds")

# NumPy is significantly faster for numerical operations
```

## Summary
Lists are more versatile and flexible, suitable for general-purpose programming, while arrays (especially NumPy arrays) are optimized for numerical computations and offer better performance and memory efficiency for homogeneous data.

### 10. Create a function to find area of circle using return statement.
--- 

In [97]:
def area_of_circle():
    r = int(input("Enter the value of r : "))
    area = 3.14*r**2
    return area

area_of_circle()

Enter the value of r :  4


50.24

In [103]:
import math

def area_of_circle(r):
    area = math.pi*r*r
    return area

area_of_circle(4)

50.26548245743669

### 11. What is the difference between print and return statement?

---
# Difference Between Print and Return Statement

## Overview
`print()` and `return` are two fundamentally different concepts in Python. `print()` is a function that displays output to the console, while `return` is a statement that sends a value back from a function.

## Key Differences

| Feature | print() | return |
|---------|---------|--------|
| Purpose | Displays output to console | Sends value back to caller |
| Type | Built-in function | Keyword/Statement |
| Usage | Can be used anywhere | Only used inside functions |
| Effect | Shows text on screen | Exits function and returns value |
| Value | Returns `None` | Returns specified value |
| Multiple Usage | Can be called multiple times | Exits function immediately |
| Function Execution | Continues execution | Terminates function |

## Examples

### Example 1: Basic Difference
```python
# Using print()
def greet_print():
    print("Hello, World!")

# Using return
def greet_return():
    return "Hello, World!"

# Calling the functions
greet_print()           # Output: Hello, World!
result1 = greet_print() # Output: Hello, World!
print(result1)          # Output: None (print returns None)

print("---")

greet_return()          # No output (return doesn't display)
result2 = greet_return()
print(result2)          # Output: Hello, World!
```

### Example 2: Using Return Value
```python
# With print - cannot use the value
def add_print(a, b):
    print(a + b)

# With return - can use the value
def add_return(a, b):
    return a + b

# Using print version
add_print(5, 3)           # Output: 8
result = add_print(5, 3)  # Output: 8
print(result)             # Output: None

# Using return version
add_return(5, 3)          # No output
result = add_return(5, 3)
print(result)             # Output: 8

# Can use returned value in calculations
total = add_return(5, 3) * 2
print(total)              # Output: 16
```

### Example 3: Multiple Statements
```python
# Multiple print statements
def multiple_prints():
    print("First line")
    print("Second line")
    print("Third line")

multiple_prints()
# Output:
# First line
# Second line
# Third line

# Multiple return attempts
def multiple_returns():
    return "First value"
    return "Second value"  # This will never execute
    print("After return")  # This will never execute

result = multiple_returns()
print(result)  # Output: First value
```

### Example 4: Practical Use Case
```python
# Bad practice - using print in calculation function
def calculate_area_print(length, width):
    area = length * width
    print(area)

# Good practice - using return
def calculate_area_return(length, width):
    area = length * width
    return area

# With print - cannot use in further calculations
calculate_area_print(5, 10)  # Output: 50
# total = calculate_area_print(5, 10) + 20  # Error! Can't add None + 20

# With return - flexible usage
area1 = calculate_area_return(5, 10)
area2 = calculate_area_return(3, 7)
total_area = area1 + area2
print(f"Total area: {total_area}")  # Output: Total area: 71
```

### Example 5: Return with Print
```python
# Using both print and return
def process_data(x):
    print(f"Processing {x}...")  # For debugging/logging
    result = x * 2
    print(f"Result calculated: {result}")  # For debugging/logging
    return result  # Return the actual value

output = process_data(5)
# Output:
# Processing 5...
# Result calculated: 10

print(f"Final output: {output}")  # Output: Final output: 10
```

### Example 6: Function Without Return
```python
# Function without explicit return
def greet(name):
    print(f"Hello, {name}!")

# Implicitly returns None
result = greet("Alice")  # Output: Hello, Alice!
print(result)            # Output: None
print(type(result))      # Output: <class 'NoneType'>
```

### Example 7: Conditional Returns
```python
def check_age(age):
    if age >= 18:
        return "Adult"
    elif age >= 13:
        return "Teenager"
    else:
        return "Child"

status = check_age(25)
print(f"Status: {status}")  # Output: Status: Adult

# With print (not useful for logic)
def check_age_print(age):
    if age >= 18:
        print("Adult")
    elif age >= 13:
        print("Teenager")
    else:
        print("Child")

# Cannot use in conditional logic
status = check_age_print(25)  # Output: Adult
if status == "Adult":  # This won't work as expected
    print("Can vote")  # Won't execute because status is None
```

## When to Use What?

### Use `print()` When:
- You want to display information to the user
- Debugging your code
- Logging program execution
- Showing intermediate results
- Creating console output

### Use `return` When:
- You need to send a value back from a function
- The value will be used in further calculations
- Building reusable functions
- Creating modular code
- The function needs to produce a result

## Summary

**print():**
- Displays output to the screen
- Returns `None`
- Used for showing information
- Doesn't affect program logic

**return:**
- Sends value back to function caller
- Exits the function immediately
- Used for producing results
- Essential for function composition and reusability

**Best Practice:** Use `return` for function output and `print()` for displaying information to users or debugging.

### 12. Create a list which includes days in a week and extract "Thursday" and "Friday".


In [104]:
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

selected_days = days[3:5]

print(selected_days)

['Thursday', 'Friday']


### 13.Write a code to generate 10 random integers between 1 to 100?

In [108]:
num = np.random.randint(1, 101, 10)
print("10 random integers between 1 to 100 : ")
num

10 random integers between 1 to 100 : 


array([72, 49, 10, 35, 73, 61, 26, 71, 52, 59], dtype=int32)

In [107]:
import random

random_numbers = random.sample(range(1, 101), 10)

print(random_numbers)


[15, 83, 55, 34, 91, 31, 68, 62, 19, 53]


### 14. What is linspace and use the same to generate 10 random numbers between 1 to 50 and find the step?

In [111]:
import numpy as np

# Generate 10 numbers between 1 and 50
numbers = np.linspace(1, 50, 10)
print("Numbers:", numbers)

# Find the step
step = numbers[1] - numbers[0]
print("Step:", step)


Numbers: [ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]
Step: 5.444444444444445


### 15. Write a code to print python 5 times?


In [119]:
for i in range(5):
    i = i+1
    print(f"{i}.python")

1.python
2.python
3.python
4.python
5.python


### 16. What makes an abstarct method different from other methods?
---

# What Makes an Abstract Method Different from Other Methods?

## Quick Overview
An abstract method is a method **without implementation** that **forces** child classes to provide their own implementation.

## Key Differences

| Feature | Abstract Method | Regular Method |
|---------|----------------|----------------|
| Implementation | No body (just definition) | Has complete code |
| Decorator | Uses `@abstractmethod` | No decorator needed |
| Must Override? | **Yes** - mandatory | No - optional |
| Class Instantiation | Cannot create object | Can create object |
| Purpose | Force subclasses to implement | Ready to use |

## Simple Example

### Abstract Method - Must Be Implemented
```python
from abc import ABC, abstractmethod

class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass  # No implementation - just a placeholder

# Error! Cannot create object of abstract class
# animal = Animal()  # TypeError

# Must implement make_sound() in child class
class Dog(Animal):
    def make_sound(self):
        return "Woof!"

class Cat(Animal):
    def make_sound(self):
        return "Meow!"

dog = Dog()
print(dog.make_sound())  # Output: Woof!

cat = Cat()
print(cat.make_sound())  # Output: Meow!
```

### Regular Method - Can Use As-Is
```python
class Animal:
    def make_sound(self):
        return "Some sound"  # Has implementation

# Can create object directly
animal = Animal()
print(animal.make_sound())  # Output: Some sound

# Child class can use parent's method or override
class Dog(Animal):
    pass  # Using parent's method

dog = Dog()
print(dog.make_sound())  # Output: Some sound
```

## Real-World Example
```python
from abc import ABC, abstractmethod

# Payment system template
class PaymentMethod(ABC):
    
    @abstractmethod
    def process_payment(self, amount):
        """Every payment method MUST implement this"""
        pass
    
    # Regular method - all classes can use
    def receipt(self, amount):
        return f"Payment of ${amount} successful"

# Must implement process_payment()
class CreditCard(PaymentMethod):
    def process_payment(self, amount):
        return f"Charged ${amount} to Credit Card"

class PayPal(PaymentMethod):
    def process_payment(self, amount):
        return f"Paid ${amount} via PayPal"

# Usage
cc = CreditCard()
print(cc.process_payment(100))  # Output: Charged $100 to Credit Card
print(cc.receipt(100))          # Output: Payment of $100 successful

paypal = PayPal()
print(paypal.process_payment(50))  # Output: Paid $50 via PayPal
```

## Why Use Abstract Methods?

### 1. **Enforce Rules**
```python
# Every vehicle MUST have start_engine method
class Vehicle(ABC):
    @abstractmethod
    def start_engine(self):
        pass
```

### 2. **Ensure Consistency**
```python
# All shapes MUST calculate area
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def area(self):
        return 3.14 * self.radius ** 2

class Square(Shape):
    def area(self):
        return self.side ** 2
```

### 3. **Create Templates**
```python
# Database template - all DB connections must implement these
class Database(ABC):
    @abstractmethod
    def connect(self):
        pass
    
    @abstractmethod
    def disconnect(self):
        pass
```

## Common Mistake - Forgetting to Implement
```python
from abc import ABC, abstractmethod

class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass
    
    @abstractmethod
    def move(self):
        pass

# Forgot to implement move() - ERROR!
class Dog(Animal):
    def make_sound(self):
        return "Woof"
    # Missing move() method!

# This will fail
# dog = Dog()  # TypeError: Can't instantiate abstract class
```

## Correct Implementation
```python
class Dog(Animal):
    def make_sound(self):
        return "Woof"
    
    def move(self):  # Now complete!
        return "Running"

dog = Dog()  # Works fine now!
```

## Summary

**Abstract Method:**
- No implementation (empty body)
- Must use `@abstractmethod` decorator
- Forces child classes to implement
- Cannot create object of abstract class
- Use when: Creating templates/blueprints

**Regular Method:**
-  Has complete implementation
-  No special decorator
-  Child class can optionally override
-  Can create object directly
-  Use when: Providing ready-to-use functionality

**Think of it this way:** Abstract methods are like a **contract** - they say "you MUST implement this method," while regular methods are like **ready-made tools** - they work immediately.

### 17. Create a program to show multiple inheritance. Use classes and methods of your choice


In [122]:
# Base class 1
class Person:
    def __init__(self, name):
        self.name = name

    def show_name(self):
        print("Name:", self.name)

# Base class 2
class Job:
    def __init__(self, job_title):
        self.job_title = job_title

    def show_job(self):
        print("Job:", self.job_title)

# Derived class (multiple inheritance)
class Employee(Person, Job):
    def __init__(self, name, job_title, salary):
        Person.__init__(self, name)
        Job.__init__(self, job_title)
        self.salary = salary

    def show_salary(self):
        print("Salary:", self.salary)

# Create an object of Employee
emp = Employee("Vinod", "Data Scientist", 90000)

# Access methods from all parent classes
emp.show_name()
emp.show_job()
emp.show_salary()


Name: Vinod
Job: Data Scientist
Salary: 90000


### 18. Create 1D array of 25 numbers. Change it to a 2D array


In [130]:
arr = np.random.randint(1,101,25)
print("25 1D array numbers : ")
display(arr)


display(arr.reshape(5,5))
print("Changed it to 2D array  ")

25 1D array numbers : 


array([76, 24, 73, 60,  7, 38,  9,  1, 40, 68, 27, 56,  7, 22, 29, 69, 67,
        2, 33,  4, 62, 47, 87, 88,  9], dtype=int32)

array([[76, 24, 73, 60,  7],
       [38,  9,  1, 40, 68],
       [27, 56,  7, 22, 29],
       [69, 67,  2, 33,  4],
       [62, 47, 87, 88,  9]], dtype=int32)

Changed it to 2D array  


### 19. Difference between extend, append and insert methods of list


# Difference Between extend(), append(), and insert()

## Quick Comparison

| Method | What It Does | Syntax | Changes List Length |
|--------|-------------|--------|-------------------|
| **append()** | Adds single item at end | `list.append(item)` | +1 |
| **extend()** | Adds multiple items at end | `list.extend(iterable)` | +n |
| **insert()** | Adds single item at specific position | `list.insert(index, item)` | +1 |

## Examples

### append() - Add ONE item at end
```python
fruits = ['apple', 'banana']
fruits.append('cherry')
print(fruits)  # ['apple', 'banana', 'cherry']

fruits.append(['mango', 'grape'])
print(fruits)  # ['apple', 'banana', 'cherry', ['mango', 'grape']]
                # Note: List added as single item
```

### extend() - Add MULTIPLE items at end
```python
fruits = ['apple', 'banana']
fruits.extend(['cherry', 'mango'])
print(fruits)  # ['apple', 'banana', 'cherry', 'mango']

fruits.extend('xy')
print(fruits)  # ['apple', 'banana', 'cherry', 'mango', 'x', 'y']
```

### insert() - Add item at SPECIFIC position
```python
fruits = ['apple', 'banana', 'cherry']
fruits.insert(1, 'mango')
print(fruits)  # ['apple', 'mango', 'banana', 'cherry']

fruits.insert(0, 'grape')
print(fruits)  # ['grape', 'apple', 'mango', 'banana', 'cherry']
```

## Side-by-Side Comparison
```python
# Starting list
list1 = [1, 2, 3]
list2 = [1, 2, 3]
list3 = [1, 2, 3]

# append() - adds as single item
list1.append([4, 5])
print(list1)  # [1, 2, 3, [4, 5]]

# extend() - adds each item separately
list2.extend([4, 5])
print(list2)  # [1, 2, 3, 4, 5]

# insert() - adds at specific index
list3.insert(1, [4, 5])
print(list3)  # [1, [4, 5], 2, 3]
```

## Quick Summary

- **append(x)** → Add `x` to the end (as one item)
- **extend([x, y])** → Add `x` and `y` to the end (separately)
- **insert(i, x)** → Add `x` at position `i`
```python
numbers = [1, 2, 3]
numbers.append(4)        # [1, 2, 3, 4]
numbers.extend([5, 6])   # [1, 2, 3, 4, 5, 6]
numbers.insert(0, 0)     # [0, 1, 2, 3, 4, 5, 6]
```

### 20. Create a list of 5 colours. Using for loops, print each element of the list along with the individual letters of the colour

In [131]:
# Create a list of colors
colors = ["Red", "Blue", "Green", "Yellow", "Purple"]

# Iterate over each color
for color in colors:
    print("Color:", color)
    print("Letters:", end=" ")
    # Iterate over each letter in the color
    for letter in color:
        print(letter, end=" ")
    print("\n")  # Newline after each color


Color: Red
Letters: R e d 

Color: Blue
Letters: B l u e 

Color: Green
Letters: G r e e n 

Color: Yellow
Letters: Y e l l o w 

Color: Purple
Letters: P u r p l e 

